language: php

php:
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/finalizer finalizer:check-final-classes ./src

after_script:
  - sh .travis.coverage.sh
