#!/usr/bin/env php
<?php
use PointingBreed\Console\CheckCodeSnifferResultCommand;
use Symfony\Component\Console\Application;
$autoloadFiles = [__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'];
$autoloaded    = false;
foreach ($autoloadFiles as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        require_once $autoloadFile;
        $autoloaded = true;
        break;
    }
}
if (! $autoloaded) {
    throw new \RuntimeException('An autoloader could not be detected: did you install this package via composer?');
}
$cli = new Application('pointingbreed');
$cli->add(new CheckCodeSnifferResultCommand());
$cli->run();
