<?php
namespace PointingBreed\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class CheckCodeSnifferResultCommand extends Command
{
    public function __construct()
    {
        parent::__construct('pointingbreed:code-sniffer:check');

        $this->setDefinition([new InputArgument('checkstyle.xml', InputArgument::REQUIRED)]);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
